### PR TITLE
Add up-pred and down-pred fns

### PR DESCRIPTION
**Pull request by tkocmathla**
This PR adds two new functions to traverse a zipper up and down, similar in spirit to next-pred, prev-prev, left-pred, and right-pred.

### CODE REVIEW

**Comment by davidsantiago** [comment]
How is this different from what you can do with child/descendant and has-child/has-descendant?

**Comment by tkocmathla** [comment]
I guess the simplest use-case is when I have a zip-loc at an element that is nested within one or more parent elements and I want to select one of those parents. I saw the existing `*-pred` functions as conveniences around zipper+selector functions, and had a need for the up direction as well.

```html
<table> <!-- I want to select this -->
  <tr>
    <td>foo</td> <!-- The zip-loc is here -->
  </tr>
</table>
```

**Comment by davidsantiago** [comment]
Ah, OK, I see. I can see your use case on up-pred. I don't think down-pred is going to be useful, because it seems unlikely that anyone really wants to go straight down the zipper, without regard to the tree structure underneath and the branches you would potentially miss.

**Comment by tkocmathla** [comment]
Good point! I actually don't have a use for down-pred but added it for symmetry. I can push a change to remove down-pred, or would you prefer a new PR?

**Comment by davidsantiago** [comment]
Just another commit is good, thanks!

**Pull request merged**
