### PR TITLE
Massive upgrade, test modernization

### PR DESCRIPTION
**Pull request by ricardojmendez**
- Removed dependency on cljx, since it was deprecated in June 2015
- Converted all files and conditionals to cljc
- Moved tests to cljs.test with doo, since cemerick.test was deprecated
  over a year ago
- Updated Clojure and ClojureScript dependencies to avoid conflicts
- Updated JSoup

Bumped version to 0.7.0 given the magnitude of the changes, and to warn
people there might be some minor breakage (the latest jsoup seems to
return the doctype string in lowercase).

### CODE REVIEW

**Comment by ricardojmendez** [comment]
Not sure what the status of the project is.  Let me know if it's not supported anymore. I might be able to take it over and push a fork to Clojars.

**Comment by ricardojmendez** [comment]
Hi David,

My goal was to remove dependencies which are already deprecated. This meant eliminating cemerick.test and cljx, and moving them to cljc. The latter is only supported from Clojure 1.7 forward, so I suppose I _could_ have left that as the lowest required version.

The only potentially non-backwards compatible change I found during tests was the issue I mentioned about the doctype string.

You're right, I may have re-formatted the code while working on Cursive to make sure additions were aligned, instead of re-formatting just the lines where I was altering the conditionals.

**Comment by ricardojmendez** [comment]
There you go. Whitespace changes rolled back on any line that I didn't have to otherwise modify to adapt to the new reader conditionals.

**Comment by ricardojmendez** [comment]
> I want to try this out on Clojure 1.7, if possible.

Sure. That should be easy enough to test. I'll leave you to it, though - next week I'm completely tied up.

> My initial instinct is to just manually make it uppercase during Hickory's parsing phase, to maintain backwards compatibility and compatibility with the CLJS version. Do you have any insight here?

My gut response was actually to keep the response as close to the underlying result as possible, but I think you're right.  If Hickory is a wrapper, it should strive to behave consistently between Clojure and ClojureScript.

**Comment by davidsantiago** [comment]
Thanks, I've released 0.7.0.

**Comment by ricardojmendez** [comment]
Perfect, glad I could help.

**Pull request merged**
